import { Button, Table } from "@heroui/react";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";
import { EditTutor } from "@/components/shared/EditTutor";
import { DeleteTutor } from "@/components/shared/DeleteTutor";
export const metadata = {
  title: "Tutor List-Tutor Find App",
  description: "Generated by create next app",
};
const MyBookTutorpage = async () => {
  const session = await auth.api.getSession({
    headers: await headers(),
  });

  console.log(session, "My Booking page");

  const user = session?.user;
  console.log(user, "user from booking page");

  const res = await fetch("http://localhost:5000/tutors");
  const tutors = await res.json();

  return (
    <div className="mx-auto h-full">{tutors.length === 0 ? (
        <div className="relative w-full h-[500px]">
          <div
            className="absolute inset-0 bg-cover bg-center"
            style={{
              backgroundImage:
                "url('https://images.unsplash.com/photo-1707396174174-df82a17309c9?q=80&w=880&auto=format&fit=crop')",
            }}
          />

          <div className="absolute inset-0 bg-red-500/60" />

          <div className="relative z-10 text-white h-full flex flex-col items-center justify-center">
            <p className="text-center font-bold text-4xl italic">
              There is no tutor yet
            </p>
          </div>
        </div>
      ) : (
        <div className="my-10">
          <h1 className="text-2xl font-bold text-center my-5">
            My Tutors
          </h1>

          <Table>
            
              <Table.Content
                aria-label="Tutors Table"
                className="min-w-[600px]"
              >
                <Table.Header>
                  <Table.Column isRowHeader>Tutor Name</Table.Column>
               
                  <Table.Column>Subject</Table.Column>
                  <Table.Column>Day & Time</Table.Column>
                  <Table.Column>Hourly Fee</Table.Column>
                  <Table.Column>Slot</Table.Column>
                  <Table.Column>Method</Table.Column>
                   <Table.Column>Action</Table.Column>

                </Table.Header>

                <Table.Body>
                  {tutors.map((tutor) => (
                    <Table.Row key={tutor._id}>
                      <Table.Cell>{tutor?.tutorname}</Table.Cell>

                    
                      <Table.Cell>{tutor?.subject}</Table.Cell>
                      <Table.Cell>{tutor?.selectDayandTime}</Table.Cell>
                      <Table.Cell>{tutor?.hourlyfee}</Table.Cell>
                      <Table.Cell>{tutor?.slot}</Table.Cell>
                      <Table.Cell>{tutor?.method}</Table.Cell>
                       <Table.Cell><div className="flex gap-3"><EditTutor tutor={tutor}/><DeleteTutor tutorId={tutor?._id}/></div></Table.Cell>

                    </Table.Row>
                  ))}
                </Table.Body>
              </Table.Content>
      
          </Table>
        </div>
      )}
    </div>
      
  );


};

export default MyBookTutorpage;