
import FilterByDate from "@/components/FilterByDate";
import  SearchTutor from "@/components/SearchTutor";
import { fetchTutors } from "@/lib/courses/data";
import Link from "next/link";
export const metadata = {
  title: "All Tutors-Tutor Find App",
  description: "Generated by create next app",
};

const TutorsPage = async({searchParams}) => {
 
 const params = await searchParams;

  const tutors = await fetchTutors({
    search: params?.search,
    startDate: params?.startDate,
    endDate: params?.endDate,
  });


  
    return (
        <div className="w-11/12 mx-auto"><h1 className="text-center text-2xl my-5 font-bold">All Tutor</h1>
        <div className="flex justify-between items-center my-7"><SearchTutor/><FilterByDate/></div><div className="grid  grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {
                tutors.map(tutor=><div className="card bg-base-100  shadow-sm" key={tutor?._id}>
  <figure className="h-48">
    <img
      src={tutor?.image}
      alt="tutor image" className=" " />
  </figure>
  <div className="card-body">
     <span className={`badge badge-s ${tutor.subject==="ICT"?"bg-blue-200":tutor.subject==="English"?"bg-amber-200":tutor.subject==="Chemistry"?"bg-green-200":tutor.subject==="Mathematics"?"bg-red-200":tutor.subject==="Biology"?"bg-orange-200":"bg-purple-200"}`}>{tutor?.subject}</span>
    <h2 className="card-title">{tutor?.tutorname}</h2>
    <p><span className="font-bold">Institute and Experience:</span>{tutor?.institution},<span className="font-bold"> Location:</span>{tutor?.location}</p>
    
    
    <div className="card-actions justify-end">
      <Link href={`/tutors/${tutor?._id}`} className="btn rounded-full bg-blue-500 text-white">Book Session</Link>
    </div>
  </div>
</div>)
            }
            
        </div></div>
        
    );
};

export default TutorsPage;