import LoginFrom from "@/components/LoginFrom"
export const metadata = {
  title: "Log In-Tutor Find App",
  description: "Generated by create next app",
};


const LogIn=()=> {
 return(<><LoginFrom/></>)
}
export default LogIn