import { BookSessionmodal } from "@/components/BookSessionmodal";
import Link from "next/link";
export const metadata = {
  title: "Tutor Details-Tutor Find App",
  description: "Generated by create next app",
};

const TutorDetailsPage = async({params}) => {
    const {id}= await params;
    const res = await fetch(`${process.env.NEXT_PUBLIC_SERVER_URL}/tutors/${id}`)
    const tutor= await res.json()
    console.log(tutor)
   
    return (
        <div className="my-10 mx-auto">
           <h1 className="text-2xl font-semibold text-center my-5">Details about <span className="text-blue-900">{tutor?.tutorname}</span></h1>
           <div className="card bg-base-100  shadow-sm"><div className="bg-blue-500"><figure className="h-100 ">
    <img
      src={tutor?.image}
      alt="tutor image" className="w-full h-[400px] object-contain object-top p-3 " />
  </figure></div>
  <div className="card-body items-center">
     <span className={`badge badge-sm ${tutor.subject==="ICT"?"bg-blue-200":tutor.subject==="English"?"bg-amber-400":tutor.subject==="Chemistry"?"bg-green-400":tutor.subject==="Mathematics"?"bg-red-400":tutor.subject==="Biology"?"bg-orange-400":"bg-purple-400"}`}>{tutor?.subject}</span>
    <h2 className="card-title">{tutor?.tutorname}</h2>
    <p><span className="font-bold">Institute and Experience:</span>{tutor?.institution},<span className="font-bold"> Location:</span>{tutor?.location}</p>
    <p><span className="font-bold">Hourly fee:</span>{tutor?.hourlyfee} , <span className="font-bold">Method:</span>{tutor?.method}</p>
    <p><span className="font-bold">Select day and time:</span>{tutor?.selectDayandTime}, <span className="font-bold">Slot:</span> {tutor?.slot}
    </p>
   <button className="badge bg-green-300">Session Date:{tutor.sessionDate}</button>
   
    
    <div className="card-actions justify-end">
      <BookSessionmodal tutor={tutor}/>
    </div>
  </div></div>
           
</div>
    
    );
};

export default TutorDetailsPage;