import { Geist, Geist_Mono } from "next/font/google";
import { ToastContainer, toast } from 'react-toastify';

import Navbar from "@/components/shared/navbar";
import Footer from "@/components/shared/footer";

import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});



export const metadata = {
  title: "Tutor Find App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={poppins.className}
    >
      <body className="min-h-full flex flex-col"><main> <Navbar/>{children} <Footer/></main><ToastContainer/></body>
    </html>
  );
}
