import AddTutor from "@/components/AddTutor";

export const metadata = {
  title: "Add tutor-Tutor Find App",
  description: "Generated by create next app",
};
const AddTutorPage = () => {
  return(<>
  <AddTutor/>
  
  </>)
  
};

export default AddTutorPage;