

import { auth } from "@/lib/auth";
import { headers } from "next/headers";
export const metadata = {
  title: "Profile-Tutor Find App",
  description: "Generated by create next app",
};
const ProfilePage = async () => {
  const session = await auth.api.getSession({
    headers: await headers(),
  });

  const user = session?.user;

  if (!user) {
    return (
      <div className="w-full flex items-center justify-center h-screen">
        <p>Please login to view your profile.</p>
      </div>
    );
  }

  return (<div><h1 className="text-2xl font-bold text-center mt-6">My Profile</h1>
    <div className="max-w-2xl mx-auto my-10 p-6 flex items-center justify-center rounded-xl shadow-sm">
      



      <div className="space-y-4">
        <div><img src={user.image} alt="Profile" className="w-24 h-24 rounded-full object-cover" /></div>
        <div>
          <p className="text-gray-500">Name</p>
          <p className="text-lg font-medium">{user.name}</p>
        </div>

        <div>
          <p className="text-gray-500">Email</p>
          <p className="text-lg font-medium">{user.email}</p>
        </div>

        <div>
          <p className="text-gray-500">User ID</p>
          <p className="text-sm">{user.id}</p>
        </div>
      </div>
    </div>
    </div>
  );
};

export default ProfilePage;